name: Generate the json-schema from the models 

on:
  push:
    branches: '**'

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Schema
        run: pip install -e ./exorde/models ; rm -rf ./exorde/models/schema.json ; python3 exorde/models/__init__.py  >> exorde/models/schema.json
      - name: Display schema
        run: cat exorde/models/schema.json
