name: Package install test

on:
  push:
    branches: '**'
 
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        pip3 install pybind11
        pip3 install -e ./schema
        pip3 install -e ./data_hub
        pip3 install -e ./client
