jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  # Replace with the desired Python version

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Install pybind11
        run: pip install pybind11

      - name: Install fasttext-langdetect and other dependencies
        run: pip install fasttext-langdetect
