name: Package installation test

on:
  push:
    branches: '**'
    paths:
      - 'client/setup.py'
      - 'data_hub/setup.py'
      - 'schema/setup.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.10
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt install -y python3.10 python3.10-dev

      - name: Install pip
        run: |
          sudo apt install python3-pip

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Install pybind11
        run: python3.10 -m pip install pybind11

      - name: Install schema
        run: python3.10 -m pip install -e ./schema

      - name: Install data_hub
        run: python3.10 -m pip install -e ./data_hub

      - name: Install client
        run: python3.10 -m pip install -e ./client
